on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy using AWS CDK
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYMENT_ROLE.ARN }}
          aws-region: us-east-1

      - name: cdk deploy
        uses: youyo/aws-cdk-github-actions@v2
        with:
          cdk_subcommand: "deploy"
          cdk_stack: "*"
          cdk_args: "--require-approval never"
          actions_comment: false
        env:
          AWS_DEFAULT_REGION: "us-east-1"
